{
    "name":"X",
    "tokens":[
         {
            "symbol":"X",
            "address":"TVWwjAYjSNrNBK7q62pgkNz6ahSyDXVTs8",
            "chainId":1,
            "decimals":18,
            "name":"X",
            "logoURI":"https://raw.githubusercontent.com/aitelong/justlists/main/IMG_1271.jpeg"
        }
   ],
    "logoURI":"https://raw.githubusercontent.com/aitelong/justlists/main/IMG_1271.jpeg",
    "version":{
        "patch":0,
        "major":1,
        "minor":1
    },
    "timestamp":1611147166000
}