{
    "name":"X",
    "tokens":[
        {
            "symbol":"WTRX",
            "address":"TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR",
            "chainId":1,
            "decimals":6,
            "name":"Wrapped TRX",
            "logoURI":"https://coin.top/production/upload/logo/TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR.png"
        },
        {
            "symbol":"USDT",
            "address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
            "chainId":1,
            "decimals":6,
            "name":"Tether USD",
            "logoURI":"https://coin.top/production/logo/usdtlogo.png"
        },
        {
            "symbol":"X",
            "address":"TVWwjAYjSNrNBK7q62pgkNz6ahSyDXVTs8",
            "chainId":1,
            "decimals":16,
            "name":"X",
            "logoURI":"https://raw.githubusercontent.com/aitelong/justlists/main/IMG_1271.jpeg"
        }
    ],
    "logoURI":"https://raw.githubusercontent.com/aitelong/justlists/main/IMG_1271.jpeg",
    "version":{
        "patch":0,
        "major":1,
        "minor":1
    },
    "timestamp":1727538985000
}